language: java

before_install:
  - chmod +x gradlew

sudo: true
dist: trusty
jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email:
    recipients:
      - rvalentim@unilurio.ac.mz
    on_success: always
    on_failure: always

after_success:
  - mvn clean test jacoco:report coveralls:report

